[package]
name = "moonbeam-rpc-primitives-debug"
authors = [ "PureStake" ]
edition = "2021"
homepage = "https://moonbeam.network"
license = "GPL-3.0-only"
repository = "https://github.com/PureStake/moonbeam/"
version = "0.1.0"

[dependencies]
environmental = { version = "1.1.2", default-features = false }
ethereum = { version = "0.14.0", default-features = false, features = [ "with-codec" ] }
ethereum-types = { version = "0.14", default-features = false }
hex = { version = "0.4", optional = true, features = [ "serde" ] }
serde = { version = "1.0", optional = true, features = [ "derive" ] }
serde_json = { version = "1.0", optional = true }

# Substrate
scale-codec = { package = "parity-scale-codec", workspace = true }
sp-api = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }

[features]
default = [ "std" ]
std = [
	"scale-codec/std",
	"environmental/std",
	"ethereum-types/std",
	"ethereum/std",
	"hex",
	"serde",
	"serde_json",
	"sp-api/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
